# Generated by Django 4.2.23 on 2025-06-25 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_emergencyhotline_alter_service_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('requirement_type', models.CharField(choices=[('text', 'Text'), ('file', 'File'), ('photo', 'Photo')], max_length=10)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requirements', to='services.service')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequestRequirementUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='service_uploads/')),
                ('value', models.TextField(blank=True, null=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='services.servicerequest')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.servicerequirement')),
            ],
        ),
    ]
